server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Serve file statis (CSS, JS, gambar) dengan benar
    location ~* \.(css|js|png|jpg|gif|ico|svg)$ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=3600";
    }

    # manifest
    location ~ ^/.*/manifest\.json$ {
        try_files /index.html =404;
        add_header Content-Type application/json;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # Semua route lain ke index.html (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }
}