server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Static files (CSS, JS, HTML, Images)
    location ~* \.(html|css|js|png|jpg|gif|ico)$ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=3600";
    }

    # Manifest.json virtual
    location ~ ^/[^/]+/manifest\.json$ {
        try_files /index.html =404;
        add_header Content-Type application/json;
        add_header Cache-Control "no-store, no-cache";
    }

    # SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}